[WIP] Add --report=json option
jfairbank/run-elm pull request #12
Opened 2018-03-17 22:44 UTC by kachkaev

Closes https://github.com/jfairbank/run-elm/issues/10

2018-03-18 10:27 UTC, kachkaev commented
This PR should be now ready for your review @jfairbank! I improved a few other bits given the opportunity, please see the git log for details.

Unfortunately, Travis CI failed initially because of this line in `.travis.yml`. A surplus row was adding to `stdout` and [broke stderr assertion](https://travis-ci.org/jfairbank/run-elm/builds/354958421):

https://github.com/jfairbank/run-elm/blob/dbf57dd3d3d79e023d746fb7558f5843cc461a7c/.travis.yml#L26

Removing `echo` from `.travis.yml` fixed this bug (https://github.com/jfairbank/run-elm/pull/12/commits/48fd2278a6a72574463309d45f50976c491419d2)

2018-03-26 09:20 UTC, kachkaev commented
ping @jfairbank 😃

2018-03-27 00:16 UTC, jfairbank requested changes
Looks good! I just had a couple of minor things.

2018-03-27 00:16 UTC, jfairbank commented on package.json
> +    "clean-test-case-projects": "cd test/integration && git clean -d -f -X",
Can we call this `test:clean` instead?

2018-03-27 00:16 UTC, jfairbank commented on CHANGELOG.md
> +Passing `--report=json` to run-elm makes Elm compilation errors `stderr` easier to parse ([#12](https://github.com/jfairbank/run-elm/pull/12))
> ...Elm compilation errors `stderr` easier to parse...

I think there is a word missing between `errors` and `` `stderr` ``.

2018-03-27 06:45 UTC, kachkaev commented
Many thanks for your review @jfairbank! Both issues are addressed 🕺

2018-03-27 22:32 UTC, jfairbank approved these changes

2018-03-27 22:33 UTC, merged

2018-03-27 22:34 UTC, jfairbank commented
Thanks again! I released v2.2.0 with these changes.